# Generated by Django 3.2.9 on 2021-12-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telePsycRxEmployees', '0002_auto_20211217_1612'),
        ('accounts', '0002_user_phone_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=250)),
                ('session_date', models.DateTimeField(auto_now=True)),
                ('session_time', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.IntegerField(null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('delinquent', 'Delinquent')], default='null', max_length=10)),
                ('date_shared', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.telepsycrxemployee')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
