# Generated by Django 3.2.9 on 2022-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='session_duration',
            new_name='ssl_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='session_time',
        ),
        migrations.AddField(
            model_name='transactions',
            name='date_paid',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ssl_merchant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ssl_pin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ssl_transaction_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ssl_txn_auth_token',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ssl_user_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subscription_type',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('delinquent', 'Delinquent')], default='freemium', max_length=50),
        ),
    ]
