# Generated by Django 3.2.9 on 2022-03-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_billing', '0002_auto_20220222_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date_paid',
            new_name='date_transaction',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='date_shared',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_merchant_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_pin',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_transaction_type',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_txn_auth_token',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='ssl_user_id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('payment_successful', 'payment_successful'), ('declined', 'declined')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='subscription_type',
            field=models.CharField(choices=[('Free_Membership', 'Free_Membership'), ('Medication_N_CareCounseling', 'Medication_N_CareCounseling'), ('Therapy', 'Therapy'), ('Medication_Therapy', 'Medication_Therapy')], default='Free_Membership', max_length=100),
        ),
    ]
