# Generated by Django 3.2.9 on 2021-12-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0002_auto_20211217_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorwaitlist',
            options={'verbose_name_plural': 'Current_Doctor_WaitList'},
        ),
        migrations.AlterModelOptions(
            name='patientwaitlist',
            options={'verbose_name_plural': 'Current_Patient_WaitList'},
        ),
    ]
