# Generated by Django 3.2.9 on 2021-12-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0003_auto_20211217_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwaitlist',
            name='on_list',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patientwaitlist',
            name='on_list',
            field=models.BooleanField(null=True),
        ),
    ]
