# Generated by Django 3.2.9 on 2022-02-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220214_1610'),
        ('telepsycrx_marketing', '0005_auto_20211221_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorwaitlist',
            name='state_of_license',
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='state_of_license',
            field=models.ManyToManyField(blank=True, null=True, related_name='license_state', to='accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='patientwaitlist',
            name='state_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_state', to='accounts.patient'),
        ),
    ]
