# Generated by Django 3.2.9 on 2022-02-14 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telepsycrx_marketing', '0006_auto_20220214_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(null=True)),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_for_suggestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
