# Generated by Django 3.2.9 on 2022-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0008_alter_doctorwaitlist_state_of_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='user_type',
            field=models.CharField(max_length=10, null=True, verbose_name='User'),
        ),
    ]
