# Generated by Django 3.2.9 on 2022-02-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0009_alter_usersuggestion_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
    ]
