# Generated by Django 3.2.9 on 2022-03-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0011_userreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorwaitlist',
            old_name='state_of_license',
            new_name='states_of_license',
        ),
        migrations.RemoveField(
            model_name='doctorwaitlist',
            name='on_list',
        ),
        migrations.RemoveField(
            model_name='patientwaitlist',
            name='on_list',
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='doctor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientwaitlist',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientwaitlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientwaitlist',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
