# Generated by Django 3.2.9 on 2022-03-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0012_auto_20220325_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwaitlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='patientwaitlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientwaitlist',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='patientwaitlist',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='last name'),
        ),
    ]
