# Generated by Django 3.2.9 on 2022-03-27 04:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0013_auto_20220326_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorwaitlist',
            name='states_of_license',
        ),
        migrations.AddField(
            model_name='doctorwaitlist',
            name='states_of_license',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
    ]
