# Generated by Django 3.2.9 on 2022-04-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_marketing', '0014_auto_20220326_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorwaitlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientwaitlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctorwaitlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='patientwaitlist',
            name='slug',
        ),
    ]
