# Generated by Django 3.2.9 on 2021-12-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211225_2241'),
        ('telepsycrx_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approved',
            new_name='Approval',
        ),
    ]
