# Generated by Django 3.2.9 on 2022-02-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_admin', '0002_rename_approved_approval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
