# Generated by Django 3.2.9 on 2021-12-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_on_waitList',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_on_waitList',
            field=models.BooleanField(null=True),
        ),
    ]
