# Generated by Django 3.2.9 on 2021-12-20 21:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211217_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.upload_to, verbose_name='images'),
        ),
    ]
