# Generated by Django 3.2.9 on 2021-12-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211220_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_on_waitList',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_on_waitList',
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_pdf_upload',
            field=models.URLField(null=True),
        ),
    ]
