# Generated by Django 3.2.9 on 2021-12-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211225_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pharmacy',
            field=models.ForeignKey(default='FakePharm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pharmacy'),
        ),
    ]
