# Generated by Django 3.2.9 on 2021-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_appointment_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
