# Generated by Django 3.2.9 on 2022-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211231_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='requester_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
