# Generated by Django 3.2.9 on 2022-02-14 23:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_hr', '0004_auto_20220214_1610'),
        ('accounts', '0013_auto_20220209_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10, null=True)),
                ('file_subject', models.CharField(max_length=100, null=True)),
                ('file', models.URLField(null=True)),
                ('upload_for_telepsycrx', models.BooleanField(default=False, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_for_upload', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientupload',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='outside_provider_email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='outside_provider_invited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='consultrequest',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='sent_to',
            field=models.ManyToManyField(related_name='consulted_to', to='accounts.Doctor'),
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='sent_to',
            field=models.ManyToManyField(related_name='referred_to', to='accounts.Doctor'),
        ),
        migrations.DeleteModel(
            name='DoctorUpload',
        ),
        migrations.DeleteModel(
            name='PatientUpload',
        ),
    ]
