# Generated by Django 3.2.9 on 2022-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
    ]
