# Generated by Django 3.2.9 on 2022-03-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_upload_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('pharmacy', models.ForeignKey(default='FakePharm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pharmacy')),
            ],
        ),
    ]
