# Generated by Django 3.2.9 on 2022-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appointmentconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepting_new_patients',
            field=models.BooleanField(default=True),
        ),
    ]
