# Generated by Django 3.2.9 on 2022-03-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_doctor_accepting_new_patients'),
        ('accounts', '0018_alter_doctor_states'),
    ]

    operations = [
    ]
