# Generated by Django 3.2.9 on 2022-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20220330_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='patient_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='reason_for_request',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='specialty',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_accepting_new_patients',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='chosen_specialty',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='requested_specialty',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultrequest',
            name='patient_full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
