# Generated by Django 3.2.9 on 2022-04-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20220331_1259'),
        ('accounts', '0020_auto_20220401_1111'),
    ]

    operations = [
    ]
