# Generated by Django 3.2.9 on 2022-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20220402_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='allDay',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
