# Generated by Django 3.2.9 on 2022-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_appointment_allday'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='appointment_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
