# Generated by Django 3.2.9 on 2022-04-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_doctor_board_certified_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='consultrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_object', to='accounts.patient'),
        ),
    ]
