# Generated by Django 3.2.9 on 2022-04-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220403_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultrequest',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='patient_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_object', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='consultrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
    ]
