# Generated by Django 3.2.9 on 2022-04-10 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220405_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelepsycrxUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20)),
                ('file_type', models.CharField(max_length=10, null=True)),
                ('file_subject', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='telepsycrx')),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='communityresource',
            name='file',
            field=models.FileField(null=True, upload_to='doctors/resources'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_pdf_upload',
            field=models.FileField(null=True, upload_to='doctors/licenses'),
        ),
        migrations.AlterField(
            model_name='lockedresource',
            name='file',
            field=models.FileField(null=True, upload_to='patient/resource_response'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='telepsycrxupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
