# Generated by Django 3.2.9 on 2022-04-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220409_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_on_waitList',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[('30', 'Half'), ('60', 'Full'), ('120', 'Double')], default='30'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recurring',
            field=models.CharField(choices=[('No', 'No'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi Monthly'), ('Annually', 'Annually')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='requester_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
