# Generated by Django 3.2.9 on 2022-04-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20220412_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height_unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='patient',
            name='height_ft',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_inch',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Free_Membership', 'Free Membership'), ('Medication_N_CareCounseling', 'Medication N Carecounseling'), ('Medication_Therapy', 'Medication Therapy'), ('Therapy', 'Therapy'), ('kg', 'Kg')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='000', max_length=20),
        ),
    ]
