# Generated by Django 3.2.9 on 2022-04-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220408_0217'),
        ('accounts', '0034_auto_20220415_1253'),
    ]

    operations = [
    ]
