# Generated by Django 3.2.9 on 2022-04-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20220416_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrequest',
            name='sent_to',
        ),
        migrations.CreateModel(
            name='ReferralRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.referralrequest')),
            ],
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='doctors',
            field=models.ManyToManyField(related_name='referred_to', through='accounts.ReferralRequestResponse', to='accounts.Doctor'),
        ),
    ]
