# Generated by Django 3.2.9 on 2022-04-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20220416_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pharmacy'),
        ),
    ]
