# Generated by Django 3.2.9 on 2022-04-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_appointment_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultrequest',
            name='patient_object',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(30, '30'), (60, '60'), (120, '120')], default=30),
        ),
    ]
