# Generated by Django 3.2.9 on 2022-04-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220419_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityresource',
            name='shared_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='communityresource',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
        migrations.AddField(
            model_name='lockedresource',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
    ]
