# Generated by Django 3.2.9 on 2022-04-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20220423_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
    ]
