# Generated by Django 3.2.9 on 2022-04-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20220422_1440'),
        ('accounts', '0040_alter_lockedresource_uploaded_by'),
    ]

    operations = [
    ]
