# Generated by Django 3.2.9 on 2022-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_merge_20220423_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_partner_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communityresource',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_accepting_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
