# Generated by Django 3.2.9 on 2022-04-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_patient_freemium_doc_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrequestresponse',
            old_name='request',
            new_name='referral',
        ),
    ]
