# Generated by Django 3.2.9 on 2022-05-01 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_rename_request_referralrequestresponse_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelepsycrxDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20)),
                ('file_type', models.CharField(max_length=10, null=True)),
                ('file_subject', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='telepsycrx/neededDocs')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
