# Generated by Django 3.2.9 on 2022-05-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_telepsycrxdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telepsycrxdownload',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='telepsycrxdownload',
            name='shared_with_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='telepsycrxdownload',
            name='shared_with_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
    ]
