# Generated by Django 3.2.9 on 2022-05-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20220430_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='appointment_for',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='reason_for_request',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
