# Generated by Django 3.2.9 on 2022-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20220430_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telepsycrxupload',
            name='file_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
