# Generated by Django 3.2.9 on 2022-05-07 00:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_telepsycrxupload_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_partner_patients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.CreateModel(
            name='RescheduleAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1', models.DateTimeField(null=True)),
                ('date_2', models.DateTimeField(null=True)),
                ('date_confirmed', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(null=True)),
                ('appointment_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.appointment')),
            ],
        ),
    ]
