# Generated by Django 3.2.9 on 2022-05-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20220509_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityresource',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
        ),
    ]
