# Generated by Django 3.2.9 on 2022-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20220509_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telepsycrxdownload',
            name='shared_with_doctor',
        ),
        migrations.RemoveField(
            model_name='telepsycrxdownload',
            name='shared_with_patient',
        ),
        migrations.AddField(
            model_name='telepsycrxdownload',
            name='shared_with_doctors',
            field=models.ManyToManyField(to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='telepsycrxdownload',
            name='shared_with_patients',
            field=models.ManyToManyField(to='accounts.Patient'),
        ),
    ]
