# Generated by Django 3.2.9 on 2022-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_communityresource_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedresponse',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communityresource',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lockedresource',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telepsycrxdownload',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telepsycrxupload',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
