# Generated by Django 3.2.9 on 2022-06-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20220524_1631'),
        ('accounts', '0052_auto_20220516_1848'),
    ]

    operations = [
    ]
