# Generated by Django 3.2.9 on 2022-06-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_merge_0051_auto_20220524_1631_0052_auto_20220516_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedresponse',
            name='shared_with_doctors',
            field=models.ManyToManyField(to='accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='annotatedresponse',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_by', to='accounts.doctor'),
        ),
    ]
