# Generated by Django 3.2.9 on 2022-06-13 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_doctor_state_license_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='state_license_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
