# Generated by Django 3.2.9 on 2022-06-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_doctor_state_license_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='isUsingDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
