# Generated by Django 3.2.9 on 2022-06-29 00:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_pharmacy_isusingdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='isUsingDelivery',
        ),
        migrations.AddField(
            model_name='patient',
            name='isUsingDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='local_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-000', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='patient first name'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='patient last name'),
        ),
    ]
