# Generated by Django 3.2.9 on 2022-07-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20220610_1302'),
        ('accounts', '0061_auto_20220628_1743'),
    ]

    operations = [
    ]
