# Generated by Django 3.2.9 on 2022-08-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_doctor_phone_activation_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='activation_expired',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_activation_expired',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_activation_token',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='activation_expired',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_activation_expired',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_activation_token',
        ),
    ]
