# Generated by Django 3.2.9 on 2022-08-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20220801_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_identified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Free_Membership', 'Free Membership'), ('Medication/CareCounseling', 'Medication N Carecounseling'), ('Medication/Therapy', 'Medication Therapy'), ('Therapy', 'Therapy'), ('Care_Counseling', 'Carecounseling'), ('Economy1_Texting', 'Economy1 Texting'), ('Economy2_Texting/Journal', 'Economy2 Texting')], max_length=70, null=True),
        ),
    ]
