# Generated by Django 3.2.9 on 2022-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20220802_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_identified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
