# Generated by Django 3.2.9 on 2022-08-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_patient_is_identified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescheduleappointment',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='rescheduleappointment',
            name='date_2',
        ),
        migrations.AddField(
            model_name='rescheduleappointment',
            name='appointment_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_1', to='accounts.appointment'),
        ),
        migrations.AddField(
            model_name='rescheduleappointment',
            name='appointment_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_2', to='accounts.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Free_Membership', 'Free Membership'), ('Medication_CareCounseling', 'Medication N Carecounseling'), ('Medication_Therapy', 'Medication Therapy'), ('Therapy', 'Therapy'), ('Care_Counseling', 'Carecounseling'), ('Economy1_Texting', 'Economy1 Texting'), ('Economy2_Texting_Journal', 'Economy2 Texting Journal')], max_length=70, null=True),
        ),
    ]
