# Generated by Django 3.2.9 on 2022-03-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appointmentconfirmation'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='session_key',
            new_name='zoom_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='session_name',
            new_name='zoom_password',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.appointment'),
        ),
    ]
