# Generated by Django 3.2.9 on 2022-04-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20220321_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='recording_status',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Error', 'Error')], max_length=20, null=True),
        ),
    ]
