# Generated by Django 3.2.9 on 2022-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_recording_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='recording_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
