# Generated by Django 3.2.9 on 2022-04-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recording_status',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Error', 'Error')], default='Not Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recording_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='session_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
