# Generated by Django 3.2.9 on 2021-12-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(null=True)),
                ('session_time', models.DateTimeField(null=True)),
                ('note', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('archived', 'Archived'), ('editable', 'Editable')], default='editable', max_length=10)),
                ('date_shared', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_notes', to='accounts.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.patient')),
            ],
            options={
                'verbose_name_plural': 'Provider Notes',
                'ordering': ['-date_created'],
            },
        ),
    ]
