# Generated by Django 3.2.9 on 2021-12-12 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20211211_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providernote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
