# Generated by Django 3.2.9 on 2021-12-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_activated'),
        ('notes', '0005_alter_providernote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providernote',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_patient_notes', to='accounts.patient'),
        ),
    ]
