# Generated by Django 3.2.9 on 2021-12-22 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211221_1929'),
        ('personal_journal', '0002_auto_20211208_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_for_provider', to='accounts.doctor'),
        ),
    ]
