# Generated by Django 3.2.9 on 2022-02-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220214_1610'),
        ('personal_journal', '0003_alter_journalentry_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='shared_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor'),
        ),
    ]
