# Generated by Django 3.2.9 on 2021-12-26 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_communityresources_doctoruploads_lockedresources_patientuploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shared', models.DateField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('is_patient', models.BooleanField(default=False, null=True)),
                ('is_doctor', models.BooleanField(default=False, null=True)),
                ('doctor_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctoruploads')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('patient_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.patientuploads')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.patient')),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('file_type', models.CharField(max_length=10, null=True)),
                ('file_subject', models.CharField(max_length=100, null=True)),
                ('file', models.URLField(null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_accepting_patients', models.BooleanField(null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
            ],
        ),
    ]
