# Generated by Django 3.2.9 on 2022-02-14 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telepsycrx_hr', '0003_alter_upload_patient_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(null=True)),
                ('is_resolved', models.BooleanField(null=True)),
                ('files_requested_by_telepsycrx', models.BooleanField(null=True)),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_for_complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='approvedfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='doctor_file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='patient_file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='ApprovedDoctor',
        ),
        migrations.DeleteModel(
            name='ApprovedFile',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
