# Generated by Django 3.2.9 on 2022-02-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_hr', '0004_auto_20220214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconcern',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Case Manager', 'Case Manager')], default='Patient', max_length=20),
        ),
    ]
