# Generated by Django 3.2.9 on 2022-02-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsycrx_hr', '0005_alter_userconcern_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconcern',
            name='files_requested_by_telepsycrx',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='userconcern',
            name='is_resolved',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
