# Generated by Django 3.2.9 on 2021-12-18 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent'), ('occasional', 'Occasional')], default='temporary', max_length=10)),
                ('employment_workType', models.CharField(choices=[('Full-time', 'Full-time'), ('part-time', 'Part-time'), ('occasional', 'Occasional')], default='full-time', max_length=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.department')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.division')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TelePsycRxEmloyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('hire_date', models.DateTimeField(null=True)),
                ('contract_start_date', models.DateTimeField(auto_now=True, null=True)),
                ('contract_end_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('new hire', 'New Hire'), ('former', 'Former'), ('terminated', 'Terminated')], default='null', max_length=10)),
                ('personal_email', models.CharField(max_length=250)),
                ('company_email', models.CharField(max_length=250)),
                ('auth_to_share', models.BooleanField(default=False)),
                ('dismissal', models.CharField(choices=[('voluntary', 'Voluntary'), ('mandated', 'Mandated')], default='null', max_length=10)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.role')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.department')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.division')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=250)),
                ('session_date', models.DateTimeField(auto_now=True)),
                ('session_time', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.IntegerField(null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('delinquent', 'Delinquent')], default='null', max_length=10)),
                ('date_shared', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.telepsycrxemloyee')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telePsycRxEmployees.division'),
        ),
    ]
